# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "false"
resume_name: "Afnan Ahmed"
resume_title: "Computer Science Graduate"

# used for the contact button in _layouts/resume.html
resume_contact_email: "afnaan.official@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+92-3214051799"
resume_contact_address: "Dha Phase 8, Lahore"

resume_header_contact_info: "Dha Phase 8, Lahore • 0321-4051799 • afnaan.official@gmail.com"
display_header_contact_info: "false"

resume_header_intro: "<p> Computer Science graduate with a strong foundation in programming, algorithms, and a keen interest in development. From
creating smooth user experience to building robust backend systems, I excel in crafting digital solutions. Whether it's
pushing the limits with innovative apps, improving user interactions, or contributing to impactful projects, I'm eager to bring
my expertise to a role that values dedication, teamwork, and a passion for excellence </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: false
resume_section_associations: false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url: "https://github.com/jglovier/resume-template"
  #resume_twitter_url: "http://twitter.com/jglovier"
  #resume_dribbble_url: "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "www.linkedin.com/in/afnan-ahmed01"
  resume_instagram_url: "afnaanzz"
  #resume_website_url: "http://joelglovier.com"
  #resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
